import React, { useState } from 'react'
import Allinsight from '../../components/ai&insight/Allinsight';
import CashFlow from '../../components/ai&insight/CashFlow';
import CostOptimization from '../../components/ai&insight/CostOptimization';
import Revenue from '../../components/ai&insight/Revenue';
import Expenses from '../../components/ai&insight/Expenses';

function AiInsights() {
  const [activeTab, setActiveTab] = useState("all");

  const tabContent = {
    all: <Allinsight />,
    cashflow: <CashFlow />,
    cost: <CostOptimization />,
    revenue: <Revenue />,
    expenses: <Expenses />,
  };

  const tabs = [
    { id: "all", label: "All Insights" },
    { id: "cashflow", label: "Cash Flow" },
    { id: "cost", label: "Cost Optimization" },
    { id: "revenue", label: "Revenue" },
    { id: "expenses", label: "Expenses" },
  ];
  return (
    <div className="p-4 max-w-[1320px] ml-[100px]  mx-auto">
      <div className="flex flex-col lg:flex-row lg:flex-nowrap items-start lg:items-center justify-between gap-4 lg:gap-0">
        <div className="flex flex-col gap-2">
          <h2 className="text-[32px] font-bold text-black">
            AI Insights & Recommendations
          </h2>
          <p className="text-md text-gray-600">
            AI-powered financial analysis and personalized recommendations
          </p>
        </div>

        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
          <button className="shadow-md bg-white border border-gray-200 text-black font-medium px-4 py-2 rounded-md flex items-center hover:bg-gray-100 transition w-full sm:w-auto justify-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="lucide lucide-zap mr-2 h-4 w-4"
            >
              <path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"></path>
            </svg>
            Generate New Analysis
          </button>

          <button className="shadow-md bg-black border border-gray-200 text-white font-medium px-4 py-2 rounded-md flex items-center hover:bg-gray-800 transition-colors duration-200 w-full sm:w-auto justify-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="lucide lucide-brain mr-2 h-4 w-4"
            >
              <path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"></path>
              <path d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z"></path>
              <path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4"></path>
              <path d="M17.599 6.5a3 3 0 0 0 .399-1.375"></path>
              <path d="M6.003 5.125A3 3 0 0 0 6.401 6.5"></path>
              <path d="M3.477 10.896a4 4 0 0 1 .585-.396"></path>
              <path d="M19.938 10.5a4 4 0 0 1 .585.396"></path>
              <path d="M6 18a4 4 0 0 1-1.967-.516"></path>
              <path d="M19.967 17.484A4 4 0 0 1 18 18"></path>
            </svg>
            Export Report
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mt-6">
        <div className="bg-white shadow-xl space-y-8 rounded-xl p-4 border border-gray-200">
          <div className="flex items-center justify-between">
            <p className="text-black font-medium">AI Insights</p>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-brain mr-2 h-4 w-4"><path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"></path><path d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z"></path><path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4"></path><path d="M17.599 6.5a3 3 0 0 0 .399-1.375"></path><path d="M6.003 5.125A3 3 0 0 0 6.401 6.5"></path><path d="M3.477 10.896a4 4 0 0 1 .585-.396"></path><path d="M19.938 10.5a4 4 0 0 1 .585.396"></path><path d="M6 18a4 4 0 0 1-1.967-.516"></path><path d="M19.967 17.484A4 4 0 0 1 18 18"></path></svg>
          </div>
          <div>
            <p className="font-bold text-black text-[24px]">0</p>
            <p className="text-gray-600">Generated by AI analysis</p>
          </div>
        </div>
        <div className="bg-white shadow-xl space-y-8 rounded-xl p-4 border border-gray-200">
          <div className="flex items-center justify-between">
            <p className="text-black font-medium">Action Required</p>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-triangle-alert h-4 w-4 text-muted-foreground"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"></path><path d="M12 9v4"></path><path d="M12 17h.01"></path></svg>
          </div>
          <div>
            <p className="font-bold text-red-500 text-[24px]">0</p>
            <p className="text-gray-600">High priority items</p>
          </div>
        </div>
        <div className="bg-white shadow-xl space-y-8 rounded-xl p-4 border border-gray-200">
          <div className="flex items-center justify-between">
            <p className="text-black font-medium">Potential Impact</p>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-target h-4 w-4 text-muted-foreground"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg>
          </div>
          <div>
            <p className="font-bold text-green-600 text-[24px]">₼0</p>
            <p className="text-gray-600">Identified opportunities</p>
          </div>
        </div>
        <div className="bg-white shadow-xl space-y-8 rounded-xl p-4 border border-gray-200">
          <div className="flex items-center justify-between">
            <p className="text-black font-medium">AI Health Score</p>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trending-up h-4 w-4 text-muted-foreground"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"></polyline><polyline points="16 7 22 7 22 13"></polyline></svg>
          </div>
          <div>
            <p className="font-bold text-blue-600 text-[24px]">100</p>
            <p className="text-gray-600">Financial health score</p>
          </div>
        </div>
      </div>
      <div className='mt-[40px]'>
        <div className="flex flex-wrap items-center text-[14px] justify-between gap-2 bg-gray-100 rounded-xl p-1">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`px-18 py-2 rounded-lg transition font-medium ${activeTab === tab.id
                ? "bg-white shadow-sm text-black font-semibold"
                : "text-gray-500 hover:text-black"
                }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="mt-6">{tabContent[activeTab]}</div>
      </div>
    </div>
  )
}

export default AiInsights